#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  orbnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"
          gateway: "172.28.0.1"

services:
  orb-domain1:
    container_name: orb1.local
    image: ghcr.io/trustbloc/orb:latest
    restart: always
    environment:
      - ORB_HOST_URL=0.0.0.0:80
      - ORB_EXTERNAL_ENDPOINT=http://orb1.local
      - DID_NAMESPACE=did:orb
      - ALLOWED_ORIGINS=http://orb1.local
      - CAS_TYPE=local
      - ANCHOR_CREDENTIAL_SIGNATURE_SUITE=Ed25519Signature2018
      - DATABASE_TYPE=mem
      - ORB_KMS_TYPE=local
      - KMSSECRETS_DATABASE_TYPE=mem
      - DEV_MODE_ENABLED=true
      - INCLUDE_PUBLISHED_OPERATIONS_IN_METADATA=true
      - INCLUDE_UNPUBLISHED_OPERATIONS_IN_METADATA=true
      - UNPUBLISHED_OPERATION_STORE_ENABLED=true
      - DID_DISCOVERY_ENABLED=true
      - BATCH_WRITER_TIMEOUT=1000
      - VCT_ENABLED=true
    ports:
      - 48326:80
    command: start
    networks:
      - "orbnet"

  orb-domain2:
    container_name: orb2.local
    image: ghcr.io/trustbloc/orb:latest
    restart: always
    environment:
      - ORB_HOST_URL=0.0.0.0:80
      - ORB_EXTERNAL_ENDPOINT=http://orb2.local
      - DID_NAMESPACE=did:orb
      - ALLOWED_ORIGINS=http://orb2.local
      - CAS_TYPE=local
      - ANCHOR_CREDENTIAL_SIGNATURE_SUITE=Ed25519Signature2018
      - DATABASE_TYPE=mem
      - ORB_KMS_TYPE=local
      - KMSSECRETS_DATABASE_TYPE=mem
      - DEV_MODE_ENABLED=true
      - INCLUDE_PUBLISHED_OPERATIONS_IN_METADATA=true
      - INCLUDE_UNPUBLISHED_OPERATIONS_IN_METADATA=true
      - UNPUBLISHED_OPERATION_STORE_ENABLED=true
      - DID_DISCOVERY_ENABLED=true
      - BATCH_WRITER_TIMEOUT=1000
      - VCT_ENABLED=true
    ports:
      - 48426:80
    command: start
    networks:
      - "orbnet"

  orb.vct:
    container_name: orb.vct
    image: ghcr.io/trustbloc/vct:v1.0.0-rc5
    restart: always
    environment:
      - VCT_API_HOST=0.0.0.0:8077
      - VCT_BASE_URL=http://orb.vct:8077
      - VCT_LOGS=maple2022:rw@orb.trillian.log.server:8090
      - VCT_KMS_TYPE=local
      - VCT_CONTEXT_PROVIDER_URL=http://orb.file-server.com:12096/ld-contexts.json
      - VCT_DSN=postgres://postgres:password@orb.postgres:5432
      - VCT_DATABASE_PREFIX=vct
    ports:
      - 8077:8077
    depends_on:
      - orb.trillian.log.server
      - orb.trillian.log.signer
      - orb.file-server.com
      - orb.postgres
    command: start
    networks:
      - "orbnet"

  orb.trillian.log.server:
    container_name: orb.trillian.log.server
    image: ghcr.io/trustbloc/vct-log-server:v1.0.0-rc5
    restart: always
    command:
      - --quota_system=noop
      - --storage_system=postgres
      - --pg_conn_str=user=postgres host=orb.postgres password=password dbname=test port=5432 sslmode=disable
      - --rpc_endpoint=0.0.0.0:8090
      - --logtostderr
    depends_on:
      - orb.postgres
    ports:
      - 8090:8090
    networks:
      - "orbnet"

  orb.trillian.log.signer:
    container_name: orb.trillian.log.signer
    image: ghcr.io/trustbloc/vct-log-signer:v1.0.0-rc5
    restart: always
    command:
      - --quota_system=noop
      - --storage_system=postgres
      - --pg_conn_str=user=postgres host=orb.postgres password=password dbname=test port=5432 sslmode=disable
      - --http_endpoint=0.0.0.0:8091
      - --force_master=true
      - --logtostderr
    depends_on:
      - orb.postgres
    ports:
      - 8091:8091
    networks:
      - "orbnet"

  orb.postgres:
    container_name: orb.postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    networks:
      - "orbnet"

  orb.file-server.com: # file server for hosting static resources (e.g. JSON-LD contexts)
    container_name: orb.file-server.com
    image: halverneus/static-file-server:latest
    environment:
      - PORT=12096
      - FOLDER=/data
      - CORS=false
      - TLS_CERT=
      - TLS_KEY=
    ports:
      - 12096:12096
    volumes:
      - ./contexts:/data
    networks:
      - "orbnet"
